SCREEN_WIDTH = 600;
SCREEN_HEIGHT = 600;
FULLSCREEN = false;

DRAW_BOXES = false;
KILL_PLAYER = true;

KEY_LEFT = "left";
KEY_RIGHT = "right";
KEY_UP = "up";
KEY_DOWN = "down";
KEY_BITE = "z";
KEY_QUIT = "escape";
KEY_START = "return";

GAMEPAD_LEFT = "dpleft";
GAMEPAD_RIGHT = "dpright";
GAMEPAD_UP = "dpup";
GAMEPAD_DOWN = "dpdown";
GAMEPAD_BITE = "a";
GAMEPAD_START = "start";
GAMEPAD_QUIT = "back";

GAMEPAD_DEADZONE = 0.75;

PLAYER_SWIM_SPEED = 200;
PLAYER_SCALE = 1;
PLAYER_INITIAL_DIMENSIONS = {
	x = 100,
	y = 100,
	w = 40,
	h = 40
};

SWIMMER_SIZE = 32;
SWIMMER_SPEED = 50;

CORPSE_SIZE = 40;

SHARK_SCALE = 0.6;
SHARK_SIZE = 80 * SHARK_SCALE;
SHARK_SPEED = 80;

HUNTER_SIZE = 55;
HUNTER_SPEED = 60;

OCEAN_MOVE_RATE = 2;
BEACH_TOP = SCREEN_HEIGHT - 520;

HUNGER_RATE = 2;
ATTENTION_RATE= 20;
EAT_RATE = 4;
CORPSE_EAT_RATE = 1.5;
SWIMMER_SPAWN_MIN = 3;
SWIMMER_SPAWN_MAX = 7;
SHARK_SPAWN_MIN = 10;
SHARK_SPAWN_MAX = 20;
HUNTER_SPAWN_MIN = 10;
HUNTER_SPAWN_MAX = 15;
CORPSE_TIMER = 10;