SCREEN_WIDTH = 600;
SCREEN_HEIGHT = 600;
FULLSCREEN = false;

DRAW_BOXES = false;

KEY_LEFT = "left";
KEY_RIGHT = "right";
KEY_UP = "up";
KEY_DOWN = "down";
KEY_QUIT = "escape";
KEY_START = "return";

GAMEPAD_LEFT = "dpleft";
GAMEPAD_RIGHT = "dpright";
GAMEPAD_UP = "dpup";
GAMEPAD_DOWN = "dpdown";
GAMEPAD_START = "start";
GAMEPAD_QUIT = "back";

GAMEPAD_DEADZONE = 0.75;

PLAYER_SWIM_SPEED = 200;
PLAYER_SCALE = 1;
PLAYER_INITIAL_DIMENSIONS = {
  x = 100,
  y = 100,
  w = 40,
  h = 40
};

OCEAN_MOVE_RATE = 2;
BEACH_TOP = SCREEN_HEIGHT - 520;
HUNGER_RATE = 1;